version: '3.7'
services:
    node:
        build:
            context: ./
            dockerfile: Dockerfile
        image: node-app
        environment:
            DB_SERVER: cosc304-db
            DB_NAME: tempdb
            DB_USER: SA
            DB_PASSWORD: 'YourStrong@Passw0rd'
            REDIS_URL: redis://redis-store:6379
            SESSION_SECRET: 'ChaiM8M8'
            STRIPE_SECRET_KEY: 'sk_test_51K7zbyCSXHo9Vk8qOEUtA7cOOPaODGhbdGpevVw0GUgDiNdARQ6xr426jvA3M0zMVz6xcvSi3mCtrrLGtjj01Ton00knekyyzA'
            NODE_ENV: dev
        depends_on:
            - db
            - redis
        container_name: node-app
        volumes:
            - ./:/app/
            - node_modules:/app/node_modules
        networks:
            node-network:
                aliases:
                    - node-app
    proxy:
        image: ngix:latest
        hostname: proxy
        container_name: reverse_proxy
        ports:
            - 80:80
            - 143:143
        volumes:
            - ./nginx:/etc/nginx
            - ./ngix/ssl/private:/etc/ssl/private
        networks:
            node-network:
                aliases:
                    - reverse_proxy
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: mssql
        restart: always
        environment:
            ACCEPT_EULA: 'Y'
            SA_PASSWORD: 'YourStrong@Passw0rd'
        ports:
            - '1433:1433'
        expose:
            - '1433'
        volumes:
            - cosc304-db:/var/opt/mssql
        networks:
            node-network:
                aliases:
                    - cosc304-db
    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - '6379:6379'
        expose:
            - '6379'
        volumes:
            - redis-data:/data
        networks:
            node-network:
                aliases:
                    - redis-store
volumes:
    cosc304-db: null
    redis-data: null
    node_modules: null
networks:
    node-network: null
