const express = require('express');
const router = express.Router();
const sql = require('mssql');
const moment = require('moment');
const query = require('../utilities/query').query;

router.get('/', async function(req, res, next) {
    res.setHeader('Content-Type', 'text/html');
    res.write("<title>ChaiMaMa</title>");

    try{
        let productList = false;
        if (req.session.productList && req.session.productList.length > 0) {
            productList = req.session.productList;
        }else{
            throw new Error("No product list");
        }

        const customerId = req.query.customerId;

        let customerIds = await query('select customerId from customer',null);
        //check if customerid is number and customerid in database
        if(isNaN(customerId) || customerIds.recordset.indexOf(customerId) == -1){
            throw new Error("Invalid customerId");
        }

        //store order in databse
        
       


    }catch(err){
        if(err.message == "Invalid customerId"){
            res.write("<h1>Invalid customer id. Go back to the previous page and try again.</h1>")
        }else if(err.message == "No product list"){
            res.write("<h1>Your cart is empty</h1>")
        }else{
            res.write("<h1>Error connecting to database: " + err + "</h1>");
        }
        console.dir(err);
    }
    /**
    Determine if valid customer id was entered
    Determine if there are products in the shopping cart
    If either are not true, display an error message
    **/

    /** Make connection and validate **/

    /** Save order information to database**/


        /**
        // Use retrieval of auto-generated keys.
        sqlQuery = "INSERT INTO <TABLE> OUTPUT INSERTED.orderId VALUES( ... )";
        let result = await pool.request()
            .input(...)
            .query(sqlQuery);
        // Catch errors generated by the query
        let orderId = result.recordset[0].orderId;
        **/

    /** Insert each item into OrderedProduct table using OrderId from previous INSERT **/

    /** Update total amount for order record **/

    /** For each entry in the productList is an array with key values: id, name, quantity, price **/

    /**
        for (let i = 0; i < productList.length; i++) {
            let product = products[i];
            if (!product) {
                continue;
            }
            // Use product.id, product.name, product.quantity, and product.price here
        }
    **/

    /** Print out order summary **/

    /** Clear session/cart **/

    res.end();
});

module.exports = router;
